
name: "Deploy"
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    
    - name: Make Sphinx
      uses: ammaraskar/sphinx-action@master
      with:
          docs-folder: "source"
          build-command: "sphinx-build . build"
    
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./source/build   
