name: "Pull Request Documentation Check"
on: [pull_request]


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Make Sphinx
      uses: ammaraskar/sphinx-action@master
      with:
          docs-folder: "source"
          build-command: "sphinx-build . build"
